name = "FLoops"
uuid = "cc61a311-1640-44b5-9fba-1b764f453329"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.2.2-DEV"

[deps]
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
FLoopsBase = "b9860ae5-e623-471e-878b-f6a53c775ea6"
InitialValues = "22cec73e-a1b8-11e9-2c92-598750a2cf9c"
JuliaVariables = "b14d175d-62b4-44ba-8fb7-3064adc8c3ec"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
BangBang = "0.3.34, 0.4"
Compat = "2.1, 3.0, 4"
FLoopsBase = "0.1.1"
InitialValues = "0.3.1"
JuliaVariables = "0.2"
MLStyle = "0.3, 0.4"
Setfield = "0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 1"
Transducers = "0.4.55"
julia = "1.6"

[extras]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Future = "9fa8497b-333b-5362-9e8d-4d0656e87820"
LiterateTest = "d77d25b0-90d3-4a16-b10a-412a9d48f625"
LoadAllPackages = "b37bcd2d-1570-475d-a8c6-9b4fae6d0ba9"
MicroCollections = "128add7d-3638-4c79-886c-908ea0c25c34"
PerformanceTestTools = "dc46b164-d16f-48ec-a853-60448fc869fe"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestFunctionRunner = "792026f5-ac9a-4a19-adcb-47b0ce2deb5d"

[targets]
test = ["Distributed", "Documenter", "Future", "LiterateTest", "LoadAllPackages", "MicroCollections", "PerformanceTestTools", "Random", "Test", "TestFunctionRunner"]
